services:
  - type: web
    name: removebg-service
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHONUNBUFFERED
        value: '1'
    plan: free
